import { UserProfile, IoTDevice, HealthReading, HealthAlert, ThresholdConfig, DeviceLog } from '../types';

export const INITIAL_THRESHOLDS: ThresholdConfig[] = [
  {
    id: 'thresh-1',
    parameter: 'heart_rate',
    name: 'Heart Rate (Pulse)',
    unit: 'BPM',
    minimum_value: 60,
    maximum_value: 100,
    enabled: true,
    description: 'Normal resting adult heart rate range (60 - 100 BPM). Values below 60 indicate bradycardia; above 100 indicate tachycardia.',
    updated_at: new Date().toISOString(),
    updated_by: 'Administrator (University Health Centre)',
  },
  {
    id: 'thresh-2',
    parameter: 'spo2',
    name: 'Blood Oxygen Saturation (SpO₂)',
    unit: '%',
    minimum_value: 95,
    maximum_value: 100,
    enabled: true,
    description: 'Normal oxygen saturation (95% - 100%). Readings below 95% indicate possible mild hypoxemia, below 90% severe hypoxemia.',
    updated_at: new Date().toISOString(),
    updated_by: 'Administrator (University Health Centre)',
  },
  {
    id: 'thresh-3',
    parameter: 'temperature',
    name: 'Body Temperature (Infrared)',
    unit: '°C',
    minimum_value: 36.5,
    maximum_value: 37.5,
    enabled: true,
    description: 'Normal physiological human body temperature (36.5°C - 37.5°C). Readings above 37.8°C trigger fever warning.',
    updated_at: new Date().toISOString(),
    updated_by: 'Administrator (University Health Centre)',
  },
  {
    id: 'thresh-4',
    parameter: 'fall_detection',
    name: 'Sudden Fall Detection (MPU6050)',
    unit: 'G-Force',
    minimum_value: 0,
    maximum_value: 3.2,
    enabled: true,
    description: 'Detects high-acceleration shock vector from 6-axis accelerometer followed by sudden stillness.',
    updated_at: new Date().toISOString(),
    updated_by: 'Administrator (University Health Centre)',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  // Student 1 (Main Demo Student)
  {
    id: 'usr-student-001',
    full_name: 'Alma Brown',
    email: 'alma.brown@student.uni.edu',
    phone: '+234 803 123 4567',
    role: 'STUDENT',
    student_id: 'UY/CS/2026/001',
    faculty: 'Computing Science',
    department: 'Computer Science',
    emergency_contact_name: 'Eleanor Brown (Mother)',
    emergency_contact_phone: '+234 803 987 6543',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Student 2
  {
    id: 'usr-student-002',
    full_name: 'Mary John',
    email: 'mary.john@student.uni.edu',
    phone: '+234 802 234 5678',
    role: 'STUDENT',
    student_id: 'UY/EE/2026/042',
    faculty: 'Engineering',
    department: 'Electrical Engineering',
    emergency_contact_name: 'Samuel John (Brother)',
    emergency_contact_phone: '+234 802 876 5432',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Student 3
  {
    id: 'usr-student-003',
    full_name: 'Peter Paul',
    email: 'peter.paul@student.uni.edu',
    phone: '+234 805 345 6789',
    role: 'STUDENT',
    student_id: 'UY/MB/2026/108',
    faculty: 'Biological Sciences',
    department: 'Microbiology',
    emergency_contact_name: 'Grace Paul (Guardian)',
    emergency_contact_phone: '+234 805 765 4321',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Student 4
  {
    id: 'usr-student-004',
    full_name: 'David James',
    email: 'david.james@student.uni.edu',
    phone: '+234 814 456 7890',
    role: 'STUDENT',
    student_id: 'UY/ME/2026/075',
    faculty: 'Engineering',
    department: 'Mechanical Engineering',
    emergency_contact_name: 'Dr. R. James (Father)',
    emergency_contact_phone: '+234 814 654 3210',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Healthcare Personnel
  {
    id: 'usr-healthcare-001',
    full_name: 'Dr. Evelyn Adams, RN',
    email: 'evelyn.adams@clinic.uni.edu',
    phone: '+234 809 555 1122',
    role: 'HEALTHCARE',
    department: 'University Health Services Clinic',
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Admin
  {
    id: 'usr-admin-001',
    full_name: 'Engr. Marcus Vance (Admin)',
    email: 'marcus.vance@admin.uni.edu',
    phone: '+234 808 999 3344',
    role: 'ADMIN',
    department: 'IoT & Systems Infrastructure Unit',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_DEVICES: IoTDevice[] = [
  {
    id: 'dev-001',
    device_uid: 'HM-ESP32-001',
    student_id: 'usr-student-001',
    student_name: 'Alma Brown',
    device_name: 'Wrist Health Monitor Unit 1',
    status: 'ONLINE',
    battery_level: 82,
    wifi_status: true,
    wifi_rssi: -58,
    last_seen: new Date(Date.now() - 12000).toISOString(),
    firmware_version: 'v1.2.4-esp32s3',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'dev-002',
    device_uid: 'HM-ESP32-002',
    student_id: 'usr-student-002',
    student_name: 'Mary John',
    device_name: 'Wrist Health Monitor Unit 2',
    status: 'ONLINE',
    battery_level: 64,
    wifi_status: true,
    wifi_rssi: -62,
    last_seen: new Date(Date.now() - 45000).toISOString(),
    firmware_version: 'v1.2.4-esp32s3',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'dev-003',
    device_uid: 'HM-ESP32-003',
    student_id: 'usr-student-003',
    student_name: 'Peter Paul',
    device_name: 'Wrist Health Monitor Unit 3',
    status: 'ONLINE',
    battery_level: 45,
    wifi_status: true,
    wifi_rssi: -71,
    last_seen: new Date(Date.now() - 30000).toISOString(),
    firmware_version: 'v1.2.4-esp32s3',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'dev-004',
    device_uid: 'HM-ESP32-004',
    student_id: 'usr-student-004',
    student_name: 'David James',
    device_name: 'Wrist Health Monitor Unit 4',
    status: 'ONLINE',
    battery_level: 21,
    wifi_status: true,
    wifi_rssi: -78,
    last_seen: new Date(Date.now() - 5000).toISOString(),
    firmware_version: 'v1.2.4-esp32s3',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'dev-005',
    device_uid: 'HM-ESP32-005',
    student_id: null,
    device_name: 'Reserve Unit 5 (Unassigned)',
    status: 'OFFLINE',
    battery_level: 95,
    wifi_status: false,
    wifi_rssi: 0,
    last_seen: new Date(Date.now() - 4 * 86400000).toISOString(),
    firmware_version: 'v1.2.4-esp32s3',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_READINGS: HealthReading[] = [
  // Alma Brown latest readings (normal state from Section 9 & 50)
  {
    id: 'read-101',
    student_id: 'usr-student-001',
    device_id: 'dev-001',
    heart_rate: 78,
    spo2: 98,
    temperature: 36.7,
    activity: 'Sitting',
    status: 'Normal',
    battery_level: 82,
    recorded_at: new Date(Date.now() - 15000).toISOString(),
  },
  {
    id: 'read-102',
    student_id: 'usr-student-001',
    device_id: 'dev-001',
    heart_rate: 76,
    spo2: 98,
    temperature: 36.7,
    activity: 'Sitting',
    status: 'Normal',
    battery_level: 82,
    recorded_at: new Date(Date.now() - 60000).toISOString(),
  },
  {
    id: 'read-103',
    student_id: 'usr-student-001',
    device_id: 'dev-001',
    heart_rate: 82,
    spo2: 97,
    temperature: 36.8,
    activity: 'Walking',
    status: 'Normal',
    battery_level: 83,
    recorded_at: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: 'read-104',
    student_id: 'usr-student-001',
    device_id: 'dev-001',
    heart_rate: 79,
    spo2: 98,
    temperature: 36.6,
    activity: 'Walking',
    status: 'Normal',
    battery_level: 83,
    recorded_at: new Date(Date.now() - 180000).toISOString(),
  },
  {
    id: 'read-105',
    student_id: 'usr-student-001',
    device_id: 'dev-001',
    heart_rate: 74,
    spo2: 99,
    temperature: 36.6,
    activity: 'Sitting',
    status: 'Normal',
    battery_level: 84,
    recorded_at: new Date(Date.now() - 240000).toISOString(),
  },

  // Mary John (Section 12: 91 BPM, 97% SpO2, 37.0°C, Walking, Normal)
  {
    id: 'read-201',
    student_id: 'usr-student-002',
    device_id: 'dev-002',
    heart_rate: 91,
    spo2: 97,
    temperature: 37.0,
    activity: 'Walking',
    status: 'Normal',
    battery_level: 64,
    recorded_at: new Date(Date.now() - 20000).toISOString(),
  },

  // Peter Paul (Section 12: 118 BPM, 95% SpO2, 37.1°C, Running, Warning)
  {
    id: 'read-301',
    student_id: 'usr-student-003',
    device_id: 'dev-003',
    heart_rate: 118,
    spo2: 95,
    temperature: 37.1,
    activity: 'Running',
    status: 'Warning',
    battery_level: 45,
    recorded_at: new Date(Date.now() - 25000).toISOString(),
  },

  // David James (Section 12: 126 BPM, 91% SpO2, 38.1°C, Sitting, Abnormal)
  {
    id: 'read-401',
    student_id: 'usr-student-004',
    device_id: 'dev-004',
    heart_rate: 126,
    spo2: 91,
    temperature: 38.1,
    activity: 'Sitting',
    status: 'Abnormal',
    battery_level: 21,
    recorded_at: new Date(Date.now() - 10000).toISOString(),
  },
];

export const INITIAL_ALERTS: HealthAlert[] = [
  {
    id: 'alt-001',
    student_id: 'usr-student-004',
    student_name: 'David James',
    reading_id: 'read-401',
    alert_type: 'High Heart Rate & Elevated Temperature',
    parameter: 'Multiple',
    value: 'HR: 126 BPM | Temp: 38.1°C | SpO₂: 91%',
    threshold: 'HR max: 100 BPM | Temp max: 37.5°C | SpO₂ min: 95%',
    severity: 'HIGH',
    message: 'Multiple physiological thresholds exceeded while sitting at rest. Tachycardia and fever detected.',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 10 * 60000).toISOString(),
    reviewed_at: null,
    resolved_at: null,
  },
  {
    id: 'alt-002',
    student_id: 'usr-student-003',
    student_name: 'Peter Paul',
    reading_id: 'read-301',
    alert_type: 'Elevated Heart Rate',
    parameter: 'Heart Rate',
    value: '118 BPM',
    threshold: '100 BPM Upper Limit',
    severity: 'WARNING',
    message: 'Heart rate elevated during running. Monitoring for post-exercise stabilization.',
    status: 'REVIEWED',
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    reviewed_at: new Date(Date.now() - 12 * 60000).toISOString(),
    reviewed_by: 'Dr. Evelyn Adams, RN',
    resolved_at: null,
    resolution_notes: 'Student verified to be performing light cardio on campus track. Recommended cool-down check in 15 mins.',
  },
];

export const INITIAL_LOGS: DeviceLog[] = [
  {
    id: 'log-001',
    device_id: 'HM-ESP32-001',
    event_type: 'DEVICE_ONLINE',
    message: 'ESP32-S3 established Wi-Fi link (SSID: UniWiFi-IoT, IP: 192.168.1.142)',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    actor: 'HM-ESP32-001 Firmware',
  },
  {
    id: 'log-002',
    device_id: 'HM-ESP32-004',
    event_type: 'ALERT_CREATED',
    message: 'Abnormal condition detected for David James (HR: 126 BPM, Temp: 38.1°C)',
    created_at: new Date(Date.now() - 600000).toISOString(),
    actor: 'Threshold Engine',
  },
  {
    id: 'log-003',
    device_id: 'HM-ESP32-001',
    event_type: 'READING_RECEIVED',
    message: 'Telemetry packet ingested: HR 78, SpO2 98, Temp 36.7, Sitting',
    created_at: new Date(Date.now() - 15000).toISOString(),
    actor: 'Supabase Ingestion',
  },
];
